
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>JoostMod</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Projectiles\Hostile\JumboCactuarWave2.png" />
    <None Remove="Projectiles\Ranged\ArmorFlame.png" />
    <None Remove="Shaders\GaussianBlurShader.fx" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="shaders\JuiceNPCShaders.fx" />
  </ItemGroup>
</Project>